// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dutyChart.Models;

namespace dutyChart.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191205191033_worker5")]
    partial class worker5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dutyChart.Models.Hour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("MaxCount");

                    b.Property<int>("MinCount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Hour");
                });

            modelBuilder.Entity("dutyChart.Models.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HourId");

                    b.Property<int>("Index");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("HourId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<int>("CountAbsencePeriod");

                    b.Property<int>("IdGroup");

                    b.Property<bool>("IsDuty");

                    b.Property<bool>("IsDutyOnLetters");

                    b.Property<bool>("IsDutyOnWedn");

                    b.Property<string>("Name");

                    b.Property<string>("_unwantedSlotsJson")
                        .HasColumnName("UnwantedSlotsJson");

                    b.HasKey("Id");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("dutyChart.Models.Slot", b =>
                {
                    b.HasOne("dutyChart.Models.Hour")
                        .WithMany("_slots")
                        .HasForeignKey("HourId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
